env: "local" # prod, dev, local
db_connection_string: "root:makas1506@tcp(127.0.0.1:3306)/URLShortener?charset=utf8&parseTime=True"
http_server:
  address: "localhost:5055"
  timeout: 4s
  idle_timeout: 60s